### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by LoicGRENON** [TeamGloomy/configtool#60]
This is the list of things we plan to add to the configurator.
If you want to get something added here, please discuss about it on [Discord ](https://discord.gg/uS97Qs7) or open **ANOTHER** [issue ](https://github.com/TeamGloomy/configtool/issues/new)as a Feature request
If you want to help and implement something yourself, feel free to.

- [ ] Add board.txt
- [ ] Add driver type for setting board.txt
- [ ] Add pins for WiFi modules
- [ ] Add extra config options for serial screens
- [ ] Add spican
- [ ] Add 12864 display support
